[package]
name = "shannon_cypher"
version = "0.1.0"
authors = ["Bernal <berrojas45@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ferris-says = "0.2.0"
bytes = "0.5"
